### ISSUE TITLE
About the test of AMASS 

### ISSUE THREAD

**Issue by LaLaLailalai** [wei-mao-2019/HisRepItself#5]
I run the command in the README file to test the pre-trained model, the error is 

>>> loading ckpt len from './checkpoint/pretrained/amass_3d_in50_out25_dctn30//ckpt_best.pth.tar'
Traceback (most recent call last):
  File "main_amass_3d_eval.py", line 105, in <module>
    main(option)
  File "main_amass_3d_eval.py", line 37, in main
    net_pred.load_state_dict(ckpt['state_dict'])
  File "/home/htang/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.gcn.gc1.weight: copying a param with shape torch.Size([60, 256]) from checkpoint, the shape in current model is torch.Size([70, 256]).
	size mismatch for module.gcn.gc7.weight: copying a param with shape torch.Size([256, 60]) from checkpoint, the shape in current model is torch.Size([256, 70]).
	size mismatch for module.gcn.gc7.bias: copying a param with shape torch.Size([60]) from checkpoint, the shape in current model is torch.Size([70]).

If the pre-train model was trained by setting the dct_n = 30?

**Comment by LaLaLailalai** [comment]
I found the name of the model is amass_3d_in50_out25_dctn30, so dct_n should be 30.
